dbt_bq_test:
  outputs:
    dev:
      dataset: dbt_bq_test
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /usr/app/dbt/dbt-bigquery-356912-c87c20b4f75b.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-bigquery-356912
      threads: 1
      type: bigquery
  target: dev
